title: "Yet Another Boring Web"
description: "Personal web site of Antonio J. García Lagar"

# Default header image
header_img:
    url: "assets/img/home-bg.jpg"

collections:
  posts:
    output: true
    sort_by: 'date'
    sort_type: 'descending'
    categories: [blog]
    comment_posts: []

comments:
    enabled: false
    disqus_shortname: "ajgarcialagares"

google_analytics:
    enabled: true
    id: UA-10547802-1
    domain: aj.garcialagar.es

social_networks:
    twitter: "ajgarlag"
    github: "https://github.com/ajgarlag"
    email: aj@garcialagar.es
    facebook:  # Your URL
    instagram: # Your id
    dribbble: # Your id
    linkedin: # Your URL

github_edit_url_base: https://github.com/ajgarlag/aj.garcialagar.es/edit/master/src/content
